backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "doors"
    label: "Doors"
    folder: "content/blog"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "Leave unchanged", readonly: true }
      - { label: "Image", name: "image", widget: "image", hint: "Not editable", disabled: true }
      - { label: "Body", name: "body", widget: "markdown" }
