backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"
site_url: "https://sutersontour.netlify.app"

collections:
  - name: "doors"
    label: "Doors"
    folder: "content/blog"
    create: false
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: image}
      - { label: "Body", name: "body", widget: "markdown" }
